config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products do
    resources :comments, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :products, only: [] do
        member do
          patch :like # /api/v1/products/:id/like
        end
      end
    end
  end

  # 原理：
  # /products/2 show
  # POST /products/2/comments, to: "comments#create"
  # DELETE /comments/3, to: "comments#destroy"

  resource :cart, only: %i[show create destroy]
  resources :cart_items, only: [:destroy]

  resource :users, except: [:destroy] do
    collection do
      get :sign_in # 登入表單
    end
    resource :sessions, only: %i[create destroy]
  end
  # pages = pages controller
  # about = action /method
  # get '/products/new', to: 'products#new', as: :new_product
  # post '/products', to: 'products#create'
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # patch '/products/:id', to: 'products#update'
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  root 'products#index'

  get '/about', to: 'pages#about', as: :about # about_path
  get '/privacy', to: 'pages#privacy'
  get '/users/sign_in', to: 'users#sign_in'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

  delegate :count, to: :cart_items

  def total_amount
    cart_items.reduce(0) do |acc, item|
      acc + (item.product.price * item.quantity)
    end.to_i
  end

  def add!(itemm)
    found_item = cart_items.find { |item| item.product == itemm.product }
    # 如果有就印出來，沒有就nil
    if found_item
      found_item.increment!(:quantity, itemm.quantity)
    else
      cart_items << itemm
    end
  end
end

app/models/cart_item.rb
# frozen_string_literal: true

class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :content, presence: true
end

app/models/likes_product.rb
# frozen_string_literal: true

class LikesProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, numericality: { greater_than: 0 }
  # validate_presence_of: Rails 3以前寫法

  belongs_to :user
  has_many :comments, -> { order(id: :desc) }

  has_many :likes_products
  has_many :liked_users, through: :likes_products, source: :user

  has_one_attached :cover
  has_one_attached :cover do |f|
    f.variant :cover, resize_to_limit: [800, 800]
    f.variant :cover_sm, resize_to_limit: [500, 500]
  end

  # scope
  # scope :ok, -> {where(deleted_at:nil)}
  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.current)
  end
end

# https://guides.rubyonrails.org/active_record_validations.html#numericality

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 3, maximum: 20 }, confirmation: true
  before_create :encrypt_password
  has_many :products
  has_many :comments
  # before_save :encrypt_password
  # after_save :send_text

  has_one :cart

  has_many :likes_products
  has_many :liked_products, through: :likes_products, source: :product

  def self.login(data)
    email = data[:email]
    password = Digest::SHA256.hexdigest("*xx#{data[:password]}yy-")

    find_by(email:, password:)
  end

  def own?(product)
    product_ids.include?(product.id)
  end

  def liked?(product)
    liked_product_ids.include?(product.id)
  end

  private

  # 設定加密，為了不想讓人看到密碼長怎麼，不管是系統管理員or駭客
  # 在存擋前面，本身這個物件的password，利用Digest::SHA.hexdigest把密碼變成奇怪的樣子
  def encrypt_password
    salted_password = "*xx#{password}yy-"
    self.password = Digest::SHA256.hexdigest(salted_password)
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: [:create]

  def show; end

  def create
    # render html:params 查看送出的東西
    item = CartItem.new(product: @product, quantity: params[:quantity])
    current_cart.add!(item)
    redirect_to @product, notice: '成功加入購物車'
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    product = Product.find(params[:product_id])
    comment = product.comments.new(comment_params)

    if comment.save
      redirect_to product_path(product), notice: '新增留言成功'
    else
      redirect_to products_path(product), alert: '留言發生錯誤'
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content).merge(user: current_user)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index; end

  def about; end

  def privacy; end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :find_product, only: [:show] # 推薦使用
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_owned_product, only: %i[edit update destroy]
  # before_action :find_product, except: [:index, :new, :create]

  # 在程式執行前做

  def index
    @products = Product.all.order(id: :desc)
    # @products= Product.where(deleted_at: nil).order(id: :desc)
    # @products = Product.order(id: :desc)
    # @products = Product.where(id: :desc)
    # @products = Product.find_by(id: :desc)
    # Product
    # 不知道要寫什麼，寫all
  end

  def show
    @comment = Comment.new
    @comments = @product.comments
    # 把.order(id: :desc)改寫到model
  end

  def edit; end

  def new
    @product = Product.new
  end

  def update
    # 1.找東西
    if @product.update(product_params)
      redirect_to product_path(@product), notice: '更新成功'
    else
      render :edit
    end
  end

  def create
    # params存入資料庫
    # @product = Product.new(product_params)
    # @product.user = current_user
    @product = current_user.products.new(product_params)

    if @product.save
      # flash[:notice] = "新增商品成功"
      redirect_to root_path, notice: '新增商品成功'
    else
      render :new
      # 借 app/views/products/new.html.erb渲染一次，所以表格內東西還在
      # redirect_to new_product_path
    end
  end

  def destroy
    find_product
    @product.destroy
    redirect_to root_path, notice: '商品已刪除'
    # 改在modal寫以下
    # @product.update(deleted_at: Time.current)
    # redirect_to root_path, alert: '商品已刪除'
  end

  private

  # render html: params
  # Strong Parameter
  def product_params
    params.require(:product)
          .permit(:title, :description, :price, :onsale, :cover)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def find_owned_product
    @product = current_user.products.find(params[:id])
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_path, notice: '註冊成功'
    else
      render :new
    end
  end

  def sign_in; end

  private

  def user_params
    params.require(:user)
          .permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cart_items_helper.rb
# frozen_string_literal: true

module CartItemsHelper
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def product_cover(product, variant = :cover_sm)
    if product.cover.attached?
      image_tag product.cover.variant(variant)
    else
      image_tag '/images/products/default.jpg'
    end
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous" defer></script>


    <title>InkMelody</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

  </head>

  <body>
    <%= render "shared/navbar"%>
    <%= render "shared/flash" if flash.any? %>
    <%#沒東西就不要渲染%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>這是關於我</h1>

<a href="/about">About</a>
<a href="<%= about_path %>" about></a>

app/views/pages/privacy.html.erb
<h1>隱私權政策</h1>
隱私權政策又稱隱私政策，是一份有關企業等資訊收集方就如何收集個人資訊所發佈的聲明，資訊收集方會在隱私權政策中提到自己收集、儲存、使用、披露和管理客戶資料的政策。資訊收集方在聲明中會告知客戶哪些具體資訊會被收集，以及這些資訊是否會被保密，是否會與合作夥伴共享，或出售給其他公司或企業。

app/views/shared/_flash.html.erb
<% [:notice, :alert].each do |type| %>
    <% if flash[type] %>
        <div data-controller="flash" class="flash-<%= type %> flex items-center justify-between">
            <%= flash[type] %>
            <button data-action="click->flash#close" class="text-black px-2 py-1 bg-white rounded">x</button>
        </div>
    <%end%>
<%end%>

app/views/shared/_form.html.erb
<% if product.errors.any? %>
  <section class="p-4 bg-rose-600 text-white p-4">
    <ul>
    <% product.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </section>
<% end %>

<%= form_with model: product,
              data: { turbo: false } do |form| %>

  <div>
    <%= form.label :cover %>
    <%= form.file_field :cover, class:'input-field' %>
  </div>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title, class: 'border-2 border-black' %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description, class: 'border-2 border-black' %>
  </div>

  <div>
    <%= form.label :price %>
    <%= form.number_field :price, class: 'border-2 border-black', min: 0 %>
  </div>

  <div>
    <%= form.label :onsale %>
    <%= form.check_box :onsale, class: 'border-2 border-black', min: 0 %>
  </div>


  <div>
    <%= form.submit class: 'bg-rose-700 text-white px-3 py-2' %>
  </div>

<% end %>

app/views/shared/_navbar.html.erb
<nav class="flex items-center justify-between px-3 py-2 text-white bg-slate-800">
    
    <div class="flex items-center gap-2">
    <h1 class="text-2xl font-bold"><%= link_to "墨韻坊", root_path %></h1>
    <ul class="flex gap-3">

        <%= link_to  "新增商品", new_product_path if user_signed_in? %>
        <li><%= link_to "商品列表", products_path %></li>
        <li><%= link_to "關於", about_path %></li>
        <li><%= link_to "隱私權", privacy_path %></li>
    </ul>
    </div>
    <div>
    <ul class="flex gap-3">
      <li class="relaitve mr-4">
        <%= link_to cart_path do %>
        <i class="fa-solid fa-cart-shopping fa-lg"></i>
          <% if current_cart.count > 0 %>
          <span class="text-xs text-center  bg-pink-400"><%= current_cart.count %></span>
          <% end %>
        <% end %>
      </li>
      <% if user_signed_in? %>
        <li><%= current_user.email %></li>
        <li><%= link_to '登出', users_sessions_path, data: { turbo_method: 'delete' } %></li>
      <% else %>
        <li><%= link_to '註冊', new_users_path %></li>
        <li><%= link_to '登入', sign_in_users_path %></li>
      <% end %>
    </ul>
    </div>
</nav>