config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products do
    resources :comments, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :products, only: [] do
        member do
          patch :like # /api/v1/products/:id/like
        end
      end
    end
  end

  # 原理：
  # /products/2 show
  # POST /products/2/comments, to: "comments#create"
  # DELETE /comments/3, to: "comments#destroy"

  resource :cart, only: %i[show create destroy]
  resources :cart_items, only: [:destroy]

  resource :users, except: [:destroy] do
    collection do
      get :sign_in # 登入表單
    end
    resource :sessions, only: %i[create destroy]
  end
  # pages = pages controller
  # about = action /method
  # get '/products/new', to: 'products#new', as: :new_product
  # post '/products', to: 'products#create'
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # patch '/products/:id', to: 'products#update'
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  root 'products#index'

  get '/about', to: 'pages#about', as: :about # about_path
  get '/privacy', to: 'pages#privacy'
  get '/users/sign_in', to: 'users#sign_in'
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items

  delegate :count, to: :cart_items

  def total_amount
    cart_items.reduce(0) do |acc, item|
      acc + (item.product.price * item.quantity)
    end.to_i
  end

  def add!(itemm)
    found_item = cart_items.find { |item| item.product == itemm.product }
    # 如果有就印出來，沒有就nil
    if found_item
      found_item.increment!(:quantity, itemm.quantity)
    else
      cart_items << itemm
    end
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_product, only: [:create]

  def show; end

  def create
    # render html:params 查看送出的東西
    item = CartItem.new(product: @product, quantity: params[:quantity])
    current_cart.add!(item)
    redirect_to @product, notice: '成功加入購物車'
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end
end

app/helpers/carts_helper.rb
# frozen_string_literal: true

module CartsHelper
end

app/views/carts/show.html.erb
<h1 class="text-2xl">購物車</h1>

<section class="grid grid-cols-3">
  <div class="col-span-2">
  <% current_cart.cart_items.each do |item| %>
    <div class="flex border border-slate-400">
      <figure class="w-32">
        <%= product_cover(item.product) %>
      </figure>

      <div class="flex justify-between w-full gap-6 p-2">
        <h3 class="text-xl font-bold">
          <%= item.product.title %>
        </h3>

        <div class="flex gap-3">
          <div><%= item.quantity %></div>

          <div>
            NT$ <%= item.product.price.to_i%>
          </div>
          <div>
            <%= link_to cart_item_path(item), data: { turbo_method: 'delete' } do %>
              <i class="fa-solid fa-trash"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
  <aside class="col-span-1 p-2">
    <h2 class="text-xl">摘要</h2>
    <ul>
      <li>總計：<%= current_cart.total_amount %></li>
    </ul>
  </aside>
</section>