config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :products do
    resources :comments, shallow: true, only: %i[create destroy]
  end

  namespace :api do
    namespace :v1 do
      resources :products, only: [] do
        member do
          patch :like # /api/v1/products/:id/like
        end
      end
    end
  end

  # 原理：
  # /products/2 show
  # POST /products/2/comments, to: "comments#create"
  # DELETE /comments/3, to: "comments#destroy"

  resource :cart, only: %i[show create destroy]
  resources :cart_items, only: [:destroy]

  resource :users, except: [:destroy] do
    collection do
      get :sign_in # 登入表單
    end
    resource :sessions, only: %i[create destroy]
  end
  # pages = pages controller
  # about = action /method
  # get '/products/new', to: 'products#new', as: :new_product
  # post '/products', to: 'products#create'
  # get '/products', to: 'products#index'
  # get '/products/:id', to: 'products#show', as: :product
  # patch '/products/:id', to: 'products#update'
  # get '/products/:id/edit', to: 'products#edit', as: :edit_product

  root 'products#index'

  get '/about', to: 'pages#about', as: :about # about_path
  get '/privacy', to: 'pages#privacy'
  get '/users/sign_in', to: 'users#sign_in'
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :title, presence: true
  validates :price, numericality: { greater_than: 0 }
  # validate_presence_of: Rails 3以前寫法

  belongs_to :user
  has_many :comments, -> { order(id: :desc) }

  has_many :likes_products
  has_many :liked_users, through: :likes_products, source: :user

  has_one_attached :cover
  has_one_attached :cover do |f|
    f.variant :cover, resize_to_limit: [800, 800]
    f.variant :cover_sm, resize_to_limit: [500, 500]
  end

  # scope
  # scope :ok, -> {where(deleted_at:nil)}
  default_scope { where(deleted_at: nil) }

  def destroy
    update(deleted_at: Time.current)
  end
end

# https://guides.rubyonrails.org/active_record_validations.html#numericality

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class ProductsController < ApplicationController
      before_action :find_product, only: [:like]
      before_action :authenticate_user!

      def like
        if current_user.liked?(@product)
          # 移除喜歡
          current_user.liked_products.destroy(@product)
          render json: { id: params[:id], status: 'unliked' }
        else
          # 加入喜歡
          current_user.liked_products << @product
          render json: { id: params[:id], status: 'liked' }
        end
      end

      private

      def find_product
        @product = Product.find(params[:id])
      end
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :find_product, only: [:show] # 推薦使用
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_owned_product, only: %i[edit update destroy]
  # before_action :find_product, except: [:index, :new, :create]

  # 在程式執行前做

  def index
    @products = Product.all.order(id: :desc)
    # @products= Product.where(deleted_at: nil).order(id: :desc)
    # @products = Product.order(id: :desc)
    # @products = Product.where(id: :desc)
    # @products = Product.find_by(id: :desc)
    # Product
    # 不知道要寫什麼，寫all
  end

  def show
    @comment = Comment.new
    @comments = @product.comments
    # 把.order(id: :desc)改寫到model
  end

  def edit; end

  def new
    @product = Product.new
  end

  def update
    # 1.找東西
    if @product.update(product_params)
      redirect_to product_path(@product), notice: '更新成功'
    else
      render :edit
    end
  end

  def create
    # params存入資料庫
    # @product = Product.new(product_params)
    # @product.user = current_user
    @product = current_user.products.new(product_params)

    if @product.save
      # flash[:notice] = "新增商品成功"
      redirect_to root_path, notice: '新增商品成功'
    else
      render :new
      # 借 app/views/products/new.html.erb渲染一次，所以表格內東西還在
      # redirect_to new_product_path
    end
  end

  def destroy
    find_product
    @product.destroy
    redirect_to root_path, notice: '商品已刪除'
    # 改在modal寫以下
    # @product.update(deleted_at: Time.current)
    # redirect_to root_path, alert: '商品已刪除'
  end

  private

  # render html: params
  # Strong Parameter
  def product_params
    params.require(:product)
          .permit(:title, :description, :price, :onsale, :cover)
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def find_owned_product
    @product = current_user.products.find(params[:id])
  end
end

app/helpers/api/v1/products_helper.rb
# frozen_string_literal: true

module Api
  module V1
    module ProductsHelper
    end
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
  def product_cover(product, variant = :cover_sm)
    if product.cover.attached?
      image_tag product.cover.variant(variant)
    else
      image_tag '/images/products/default.jpg'
    end
  end
end

app/views/products/_product.html.erb
<li class="p-2 border rounded-sm shadow-sm border-slate-300">
    <div>
        <%= link_to product_path(product) do %>
            <figure>
                <%= product_cover(product) %>
            </figure>
        <% end %>
        <h2 class="font-bold"><%= link_to product.title, product_path(product)%></h2>
        <span>NT$<%= product.price %></span>
        <p class="text-slate-400"><%= product.description %></p>
    </div>
</li>

app/views/products/edit.html.erb
<h1>編輯商品</h1>
<%= render 'shared/form', product: @product %>

app/views/products/index.html.erb
<p class="fs-5 p-1">商品列表</p>
<%= link_to  "新增商品", new_product_path, class: 'ink-btn' if user_signed_in? %>
<ul class="grid grid-cols-2 md:grid-cols-3  lg:grid-cols-4 gap-3">
<% @products.each do |product|%>
  <%= render 'product', product: %>
<%end%>
</ul>

app/views/products/new.html.erb
<h1>新增商品</h1>
<%= render 'shared/form', product: @product %>

app/views/products/old.html.erb
<%# <form action="/products" method="post"
data-turbo="false">
<div class="title">
  <label for="title">Products</label>
  <input name="product[products]" type="text" id="title" class="border-2 border-black"></input>
</div>

<input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

<div class="description">
  <label for="description">Description</label>
  <textarea name="product[description]" id="description" class="border-2 border-black"></textarea>
</div>

<div class="price">
  <label for="price">Price</label>
  <input name="product[price]" type="number" id="price" class="border-2 border-black" />
</div>
  <button>送出</button>
</form> %>

app/views/products/show.html.erb
<% if  user_signed_in? and current_user.own?(@product) %>
  <%= link_to "編輯商品", edit_product_path, class: 'ink-btn' %>
  <%# product_path(@product) 是指向  # put '/products/:id', to: 'products#update' %>
  <%= link_to '刪除商品', product_path(@product), class: 'ink-btn ink-btn-danger', data: {
   turbo_method: 'delete',
   turbo_confirm: '確認刪除？'
 } %>
<% end %>



<section class="grid grid-cols-1 sm:grid-cols-3 gap-3">
  <div>
    <%= image_tag @product.cover.variant(:cover) if @product.cover.attached? %>
  </div>
  <div class="col-span-1 p-3">
    <%= form_with   url: cart_path,
                    data:{turbo:false},
                    class: 'flex flex-col gap-3' do |form| %>
    <%= form.hidden_field :id, value: @product.id %> 
    
      <h3 class="text-2xl"><%= @product.title %></h3>
      <div>
        <%= form.select :quantity, (1..10).to_a, {}, class: 'text-lg border border-slate-300 p-2' %>
      </div>
      <h3>售價:<%= @product.price %>元</h3>
      <p>描述:<%= simple_format(@product.description) %></p>
        <div data-controller="like" data-liked="<%= current_user&.liked?(@product) %>" data-id="<%= @product.id %>">
          <%= link_to '喜歡', '#', class: 'ink-btn w-full text-center', data: {
            action: 'like#toggle',
            like_target: 'btn'
          } %>
        </div>
        <div>
          <%= form.submit '加入購物車', class: 'ink-btn w-full' %>
        </div>
    <% end %>
  </div>

</section>

<section>
  <h3 class="text-xl">留言</h3>
  <%= form_with(model: [@product, @comment],
                data: { turbo: false, local: false }) do |f| %>
  <div>
      <%= f.text_area :content, class: 'input-field' %>
  </div>
      <%= f.submit '留言', class:'ink-btn' %>
      <% end %>
</section>




<ul>
<% @comments.each do |comment| %>
<li><%= comment.content %></li>
<% end %>
<ul>